[project]
name = "kraken-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "click>=8.3.1",
    "dotenv>=0.9.9",
    "ipykernel>=7.1.0",
    "openai>=2.15.0",
    "rich>=14.3.1",
]
